account_name:
  regular_expression: /^[a-zA-Z0-9_]{1,99}$/
payment_data_types:
  keyhash_hex:      '01'
  scripthash_hex:   '02'
  payment_code_hex: '03'
  stealth_keys_hex: '04'
op_return:
  protocol_hex: '01010101'
account_number:
  block_modification_value: 563620
identicons:
  - index:     0
    codepoint: 128123
    string:    ğŸ‘»
  - index:     1
    codepoint: 128018
    string:    ğŸ’
  - index:     2
    codepoint: 128021
    string:    ğŸ•
  - index:     3
    codepoint: 128008
    string:    ğŸˆ
  - index:     4
    codepoint: 128014
    string:    ğŸ
  - index:     5
    codepoint: 128004
    string:    ğŸ„
  - index:     6
    codepoint: 128022
    string:    ğŸ–
  - index:     7
    codepoint: 128016
    string:    ğŸ
  - index:     8
    codepoint: 128042
    string:    ğŸª
  - index:     9
    codepoint: 128024
    string:    ğŸ˜
  - index:     10
    codepoint: 128000
    string:    ğŸ€
  - index:     11
    codepoint: 128007
    string:    ğŸ‡
  - index:     12
    codepoint: 128063
    string:    ğŸ¿
  - index:     13
    codepoint: 129415
    string:    ğŸ¦‡
  - index:     14
    codepoint: 128019
    string:    ğŸ“
  - index:     15
    codepoint: 128039
    string:    ğŸ§
  - index:     16
    codepoint: 129414
    string:    ğŸ¦†
  - index:     17
    codepoint: 129417
    string:    ğŸ¦‰
  - index:     18
    codepoint: 128034
    string:    ğŸ¢
  - index:     19
    codepoint: 128013
    string:    ğŸ
  - index:     20
    codepoint: 128031
    string:    ğŸŸ
  - index:     21
    codepoint: 128025
    string:    ğŸ™
  - index:     22
    codepoint: 128012
    string:    ğŸŒ
  - index:     23
    codepoint: 129419
    string:    ğŸ¦‹
  - index:     24
    codepoint: 128029
    string:    ğŸ
  - index:     25
    codepoint: 128030
    string:    ğŸ
  - index:     26
    codepoint: 128375
    string:    ğŸ•·
  - index:     27
    codepoint: 127803
    string:    ğŸŒ»
  - index:     28
    codepoint: 127794
    string:    ğŸŒ²
  - index:     29
    codepoint: 127796
    string:    ğŸŒ´
  - index:     30
    codepoint: 127797
    string:    ğŸŒµ
  - index:     31
    codepoint: 127809
    string:    ğŸ
  - index:     32
    codepoint: 127808
    string:    ğŸ€
  - index:     33
    codepoint: 127815
    string:    ğŸ‡
  - index:     34
    codepoint: 127817
    string:    ğŸ‰
  - index:     35
    codepoint: 127819
    string:    ğŸ‹
  - index:     36
    codepoint: 127820
    string:    ğŸŒ
  - index:     37
    codepoint: 127822
    string:    ğŸ
  - index:     38
    codepoint: 127826
    string:    ğŸ’
  - index:     39
    codepoint: 127827
    string:    ğŸ“
  - index:     40
    codepoint: 129373
    string:    ğŸ¥
  - index:     41
    codepoint: 129381
    string:    ğŸ¥¥
  - index:     42
    codepoint: 129365
    string:    ğŸ¥•
  - index:     43
    codepoint: 127805
    string:    ğŸŒ½
  - index:     44
    codepoint: 127798
    string:    ğŸŒ¶
  - index:     45
    codepoint: 127812
    string:    ğŸ„
  - index:     46
    codepoint: 129472
    string:    ğŸ§€
  - index:     47
    codepoint: 129370
    string:    ğŸ¥š
  - index:     48
    codepoint: 129408
    string:    ğŸ¦€
  - index:     49
    codepoint: 127850
    string:    ğŸª
  - index:     50
    codepoint: 127874
    string:    ğŸ‚
  - index:     51
    codepoint: 127853
    string:    ğŸ­
  - index:     52
    codepoint: 127968
    string:    ğŸ 
  - index:     53
    codepoint: 128663
    string:    ğŸš—
  - index:     54
    codepoint: 128690
    string:    ğŸš²
  - index:     55
    codepoint: 9973
    string:    â›µ
  - index:     56
    codepoint: 9992
    string:    âœˆ
  - index:     57
    codepoint: 128641
    string:    ğŸš
  - index:     58
    codepoint: 128640
    string:    ğŸš€
  - index:     59
    codepoint: 8986
    string:    âŒš
  - index:     60
    codepoint: 9728
    string:    â˜€
  - index:     61
    codepoint: 11088
    string:    â­
  - index:     62
    codepoint: 127752
    string:    ğŸŒˆ
  - index:     63
    codepoint: 9730
    string:    â˜‚
  - index:     64
    codepoint: 127880
    string:    ğŸˆ
  - index:     65
    codepoint: 127872
    string:    ğŸ€
  - index:     66
    codepoint: 9917
    string:    âš½
  - index:     67
    codepoint: 9824
    string:    â™ 
  - index:     68
    codepoint: 9829
    string:    â™¥
  - index:     69
    codepoint: 9830
    string:    â™¦
  - index:     70
    codepoint: 9827
    string:    â™£
  - index:     71
    codepoint: 128083
    string:    ğŸ‘“
  - index:     72
    codepoint: 128081
    string:    ğŸ‘‘
  - index:     73
    codepoint: 127913
    string:    ğŸ©
  - index:     74
    codepoint: 128276
    string:    ğŸ””
  - index:     75
    codepoint: 127925
    string:    ğŸµ
  - index:     76
    codepoint: 127908
    string:    ğŸ¤
  - index:     77
    codepoint: 127911
    string:    ğŸ§
  - index:     78
    codepoint: 127928
    string:    ğŸ¸
  - index:     79
    codepoint: 127930
    string:    ğŸº
  - index:     80
    codepoint: 129345
    string:    ğŸ¥
  - index:     81
    codepoint: 128269
    string:    ğŸ”
  - index:     82
    codepoint: 128367
    string:    ğŸ•¯
  - index:     83
    codepoint: 128161
    string:    ğŸ’¡
  - index:     84
    codepoint: 128214
    string:    ğŸ“–
  - index:     85
    codepoint: 9993
    string:    âœ‰
  - index:     86
    codepoint: 128230
    string:    ğŸ“¦
  - index:     87
    codepoint: 9999
    string:    âœ
  - index:     88
    codepoint: 128188
    string:    ğŸ’¼
  - index:     89
    codepoint: 128203
    string:    ğŸ“‹
  - index:     90
    codepoint: 9986
    string:    âœ‚
  - index:     91
    codepoint: 128273
    string:    ğŸ”‘
  - index:     92
    codepoint: 128274
    string:    ğŸ”’
  - index:     93
    codepoint: 128296
    string:    ğŸ”¨
  - index:     94
    codepoint: 128295
    string:    ğŸ”§
  - index:     95
    codepoint: 9878
    string:    âš–
  - index:     96
    codepoint: 9775
    string:    â˜¯
  - index:     97
    codepoint: 128681
    string:    ğŸš©
  - index:     98
    codepoint: 128099
    string:    ğŸ‘£
  - index:     99
    codepoint: 127838
    string:    ğŸ
